# Generated by Django 5.1.1 on 2024-11-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_sosrequest_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sosrequest',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='sosrequest',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
