# Generated by Django 5.1.1 on 2024-10-02 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_is_phone_verified_profile_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_phone_verified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='otp',
        ),
    ]
