# Generated by Django 5.1.1 on 2024-10-15 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_booking_checkin_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='location',
        ),
    ]
