# Generated by Django 5.1.1 on 2024-11-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_accommodation_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('medical', 'Medical'), ('police', 'Police'), ('fire', 'Fire Brigade'), ('other', 'Other')], max_length=50)),
            ],
        ),
    ]
