# Generated by Django 5.1.1 on 2024-11-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_rename_timestamp_sosrequest_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sosrequest',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='sosrequest',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
